name: Build and Test

on: [push, pull_request, pull_request_target]

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Tests with Code Coverage
        run: |
          coverage run manage.py test
          coverage xml -o coverage.xml
        if: success()
        continue-on-error: true

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.xml
        if: success()
        continue-on-error: true

      - name: Analysing the code with pylint
        run: |
          pip install pylint
          pylint $(git ls-files '*.py')
        continue-on-error: true
        if: success()
